version: '3.1'

services:

    mysql:
        image: mysql
        restart: always
        ports:
           - 3306:3306
        volumes:
            - ./etc/mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root!
